{"uuid": "91e70969-6a7a-419b-ba7e-644a070ffa81", "children": ["3a135d08-35c8-4401-8390-bdcfe8ef6ed8"], "befores": [{"name": "connection_fixture", "status": "broken", "statusDetails": {"message": "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 429\n", "trace": "  File \"/home/krab/.local/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/krab/.local/lib/python3.6/site-packages/_pytest/fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/krab/.local/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/home/krab/.local/lib/python3.6/site-packages/pytest_asyncio/plugin.py\", line 97, in wrapper\n    return loop.run_until_complete(setup())\n  File \"/usr/lib/python3.6/asyncio/base_events.py\", line 484, in run_until_complete\n    return future.result()\n  File \"/home/krab/.local/lib/python3.6/site-packages/pytest_asyncio/plugin.py\", line 78, in setup\n    res = await gen_obj.__anext__()\n  File \"/home/krab/PycharmProjects/bitfinex/websocket_API/conftest.py\", line 11, in connection_fixture\n    ws_connection = await websockets.connect(URI)\n  File \"/home/krab/.local/lib/python3.6/site-packages/websockets/client.py\", line 547, in __await_impl__\n    extra_headers=protocol.extra_headers,\n  File \"/home/krab/.local/lib/python3.6/site-packages/websockets/client.py\", line 296, in handshake\n    raise InvalidStatusCode(status_code)\n"}, "start": 1582626356818, "stop": 1582626357030}], "afters": [{"name": "connection_fixture::finalizer", "status": "passed", "start": 1582626357098, "stop": 1582626357098}], "start": 1582626356818, "stop": 1582626357098}